
    @section('mainslider')
        <div class="mfn-main-slider" id="mfn-rev-slider">
            <div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
                <div id="rev_slider_1_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8">
                    <ul>
                        <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-rotate="0" data-saveperformance="off" data-title="Slide"
                            data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                            <img src="images/home_school2_slider_bg.jpg" title="home_school2_slider_bg" width="1920" height="660" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                            <div class="tp-caption   tp-resizeme" id="slide-1-layer-1" data-x="right" data-hoffset="60" data-y="139" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'
                                 data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 600; color: #fdc73e; letter-spacing: 0px;font-family:Poppins;">
                                WELCOME ON OUR SITE
                            </div>
                            <div class="tp-caption   tp-resizeme" id="slide-1-layer-2" data-x="right" data-hoffset="59" data-y="177" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'
                                 data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 80px; line-height: 80px; font-weight: 400; color: #ffffff; letter-spacing: 0px;font-family:PT Serif;">
                                Primary School
                            </div>
                            <div class="tp-caption   tp-resizeme" id="slide-1-layer-3" data-x="right" data-hoffset="60" data-y="281" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'
                                 data-textAlign="['right','right','right','right']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 18px; line-height: 25px; font-weight: 400; color: #ffffff; letter-spacing: 0px;font-family:PT Serif;">
                                Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse
                                <br> a pellentesque dui, non felis. Maecenas malesuada elit lectus.
                            </div>
                            <a class="tp-caption rev-btn  tp-resizeme" href="about.html" target="_self" id="slide-1-layer-5" data-x="right" data-hoffset="60" data-y="377" data-width="['auto']" data-height="['auto']" data-type="button" data-actions='' data-responsive_offset="on"
                               data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,32,29);bs:solid;bw:0 0 0 0;"}]'
                               data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[15,15,15,15]" data-paddingright="[35,35,35,35]" data-paddingbottom="[15,15,15,15]" data-paddingleft="[35,35,35,35]" style="z-index: 8; white-space: nowrap; font-size: 16px; line-height: 17px; font-weight: 400; color: rgba(255,255,255,1); letter-spacing: px;font-family:PT Serif;background-color:rgb(236,61,58);border-color:rgba(0,0,0,1);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">Learn more <i class="icon-right-open"></i> </a>
                            <a
                                class="tp-caption rev-btn  tp-resizeme" href="teachers.html" target="_self" id="slide-1-layer-7" data-x="30" data-y="bottom" data-voffset="61" data-width="['320']" data-height="['auto']" data-type="button"
                                data-actions='' data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,32,29);bs:solid;bw:0 0 0 0;"}]'
                                data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[25,25,25,25]" data-paddingright="[35,35,35,35]" data-paddingbottom="[25,25,25,25]" data-paddingleft="[35,35,35,35]" style="z-index: 9; min-width: 320px; max-width: 320px; white-space: nowrap; font-size: 19px; line-height: 22px; font-weight: 700; color: rgba(255,255,255,1); letter-spacing: px;font-family:PT Serif;background-color:rgb(236,61,58);border-color:rgba(0,0,0,1);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">Our teachers <i class="icon-right-open"></i> </a><a class="tp-caption rev-btn  tp-resizeme" href="classes.html" target="_self" id="slide-1-layer-8" data-x="center" data-hoffset="-1" data-y="bottom" data-voffset="60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         data-width="['320']" data-height="['auto']" data-type="button" data-actions='' data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(229,178,48);bs:solid;bw:0 0 0 0;"}]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[25,25,25,25]" data-paddingright="[35,35,35,35]" data-paddingbottom="[25,25,25,25]" data-paddingleft="[35,35,35,35]" style="z-index: 10; min-width: 320px; max-width: 320px; white-space: nowrap; font-size: 19px; line-height: 22px; font-weight: 700; color: rgba(255,255,255,1); letter-spacing: px;font-family:PT Serif;background-color:rgb(252,185,39);border-color:rgba(0,0,0,1);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">All classes <i class="icon-right-open"></i> </a>
                            <a
                                class="tp-caption rev-btn  tp-resizeme" href="contact.html" target="_self" id="slide-1-layer-9" data-x="right" data-hoffset="28" data-y="bottom" data-voffset="60" data-width="['320']" data-height="['auto']"
                                data-type="button" data-actions='' data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(0,0,0);bg:rgb(237,237,237);bs:solid;bw:0 0 0 0;"}]'
                                data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[25,25,25,25]" data-paddingright="[35,35,35,35]" data-paddingbottom="[25,25,25,25]" data-paddingleft="[35,35,35,35]" style="z-index: 11; min-width: 320px; max-width: 320px; white-space: nowrap; font-size: 19px; line-height: 22px; font-weight: 700; color: #000000; letter-spacing: px;font-family:PT Serif;background-color:rgb(255,255,255);border-color:rgba(0,0,0,1);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">Contact us <i class="icon-right-open"></i> </a>
                            <div class="tp-caption   tp-resizeme" id="slide-1-layer-10" data-x="288" data-y="bottom" data-voffset="74" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'
                                 data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;"><img src="images/home_school2_pic10.png" data-ww="44px" data-hh="44px" width="44" height="44" data-no-retina>
                            </div>
                            <div class="tp-caption   tp-resizeme" id="slide-1-layer-11" data-x="center" data-hoffset="125" data-y="bottom" data-voffset="73" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on"
                                 data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']"
                                 data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13;"><img src="images/home_school2_pic11.png" data-ww="41px" data-hh="41px" width="41" height="41" data-no-retina>
                            </div>
                            <div class="tp-caption tp-resizeme" id="slide-1-layer-12" data-x="right" data-hoffset="43" data-y="bottom" data-voffset="75" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on"
                                 data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']"
                                 data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14;"><img src="images/home_school2_pic12.png" data-ww="37px" data-hh="42px" width="37" height="42" data-no-retina>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    @endsection


